cmake_minimum_required(VERSION 3.6) 

# Pass your lists in quations, for example:
# PRINT_FILES("${file_list}")
MACRO(PRINT_FILES file_list)
    foreach(thing ${file_list})
        message(STATUS " |-- ${thing}")
    endforeach()
    message("----------------------------------------------------------------------------------------------------------------")
    message(" ")
ENDMACRO()

MACRO(PRINT_MODULE_FILES module_name sources_list includes_list)
    if(VERBOSE_FILE_INCLUSION)
        message(STATUS "${module_name} library files are:")
        message(STATUS "=====Source Files=====")
        PRINT_FILES("${sources_list}")
        message(STATUS "=====Include Files=====")
        PRINT_FILES("${includes_list}")
    endif()
ENDMACRO()

FUNCTION(INCLUDE_DIRS directory_list)
    foreach(directory IN LISTS ${directory_list})
        if(VERBOSE_FILE_INCLUSION)
            message(STATUS "Including directory: ${directory}")
        endif()
        include_directories(${directory})
    endforeach()
ENDFUNCTION()

FUNCTION(INCLUDE_DIRS_AND_FILES directory_list included_file_list)
    INCLUDE_DIRS(${directory_list})
    foreach(directory IN LISTS ${directory_list})
        file(GLOB tmp_file_list ${directory}/*.hpp)
        if(VERBOSE_FILE_INCLUSION)
            message(STATUS "Including files: ${tmp_file_list}")
        endif()
        list(APPEND included_file_list ${tmp_file_list})
    endforeach()
    set(${included_file_list} ${${included_file_list}} PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(WRITE_PKG_CONFIG_IN_FILE this_project)
    if(EXISTS ${PROJECT_SOURCE_DIR}/${this_project}Config.cmake.in)
        message(STATUS "Pacakge input file: ${PROJECT_SOURCE_DIR}/${this_project}Config.cmake.in already exists")
    else()
    message(STATUS "Creating package input file: ${PROJECT_SOURCE_DIR}/${this_project}Config.cmake.in")
    file(WRITE ${PROJECT_SOURCE_DIR}/${this_project}Config.cmake.in
        "@PACKAGE_INIT@ 
include(\"\${CMAKE_CURRENT_LIST_DIR}/@PROJECT_NAME@Targets.cmake\")
check_required_components(\"@PROJECT_NAME@\")")
    endif()
ENDFUNCTION()